version: "3"

services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1 
      - TES_PATH=/usr/bin/tesseract
      - AZURE_BLOB_STOR_CONN=DefaultEndpointsProtocol=https;AccountName=ssmtest2;AccountKey=F6wNhZnDUHh7vEw6bxeQb2yrz1Iqw1GPh9uLqwPwxjBUCNjYro3TGUum/kFnr25tG/fWzrqpauVhPnKUEPZAwA==;EndpointSuffix=core.windows.net
      - AZURE_BLOB_CONT_NAME=images
      - AZURE_SERV_BUS_CONN=Endpoint=sb://ssm-test.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=4866x+b6U/qzuzNUK6upkZ0McMVEliCP8Skg2du7DM0=
      - AZURE_SERV_QUE_NAME=queue1
      - AZURE_SERV_TOP_SEND=topic1
    command: flask run --host=0.0.0.0 --port=80
